17th yoshikazu kuramoto
tajisoft/droneschool pull request #12
Opened 2024-06-19 05:13 UTC by yoshizo34

Workshop準備の8.pull requestです

2024-06-19 09:12 UTC, tajisoft commented
もとのファイルを編集せず、ご自身のフォルダに写経してから編集等をお願いいたします。

2024-06-19 10:32 UTC, tajisoft requested changes

2024-06-19 10:32 UTC, tajisoft commented on pymavlink_scripts/pm01_message_dump.py
> -    "tcp:127.0.0.1:5762", source_system=1, source_component=90)
養成塾で用意しているファイルへの直接編集はせずに、このファイルをご自身のフォルダにコピーもしくは写経してください。

2024-06-19 13:30 UTC, yoshizo34 commented on pymavlink_scripts/pm01_message_dump.py
> -    "tcp:127.0.0.1:5762", source_system=1, source_component=90)
承知しました。失礼しました。

2024-06-19 13:32 UTC, yoshizo34 commented
修正しました。

2024-06-19 23:09 UTC, merged

2024-06-19 23:10 UTC, tajisoft commented
今回はコンフリクトないためマージしました！
みんなが触りそうなファイルはコンフリクトしやすいので、次発生した場合はぜひ該当コミットの取り消しにトライしてみてください〜！

https://qiita.com/shuntaro_tamura/items/06281261d893acf049ed

2024-06-20 08:54 UTC, yoshizo34 commented
承知しました。情報ありがとうございます。
二つのSDを入れ替えながらやったせいで、変なことになっていました。
次からは気をつけます。